import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import styled from 'styled-components';
import Vimeo from '@u-wave/react-vimeo';
import { useEffect, useState } from 'react';

const Homepage = (props) => {
  const [videoID, setVideoID] = useState('764818684');

  useEffect(() => {
    setVideoID(props.videoUID);
  }, [props.videoUID]);

  return (
    <StyledHomepage>
      <Head>
        <title>{props.page.data.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className="header-image">
          <Image src="/nenuco.png" alt="Nenuco" width="260" height="80"/>
        </div>
      </header>
      <main>
        <div className="vimeo-container">
          <div className="vimeo-loading"></div>
          <Vimeo
            video={videoID}
            // autoplay
            responsive
            onReady={() => {
              document.querySelector('.vimeo-loading').style.opacity = 0;
            }}
          />
        </div>
        <section className="video-gallery">
          <ul>
            {props.videoPosts.map((e, i) => {
              return (
                <StyledVideoPostLink href={e.uid} key={i} colorDominant={e.data.color_dominant}>
                  <li 
                    style={{
                      backgroundImage: `url(${e.data.thumbnail.url})`
                    }}
                    className="video-thumbnail"
                  >
                  </li>
                </StyledVideoPostLink>
              )
            })}
          </ul>
        </section>
      </main>
      <footer>

      </footer>
    </StyledHomepage>
  )
};

const StyledVideoPostLink = styled(Link)`
  li {
    list-style: none;
    display: flex;
    text-align: center;
    height: 340px;
    justify-content: center;
    background-size: cover;
    background-position: center;
    border-radius: 5px;
    transition: 0.15s ease-in-out all;
    position: relative;
    &:hover {
      opacity: 1 !important;
      /* box-shadow: 0 0 20px 2px ${props => props.colorDominant}; */
      border: 3px solid ${props => props.colorDominant};
      transform: scale(1.05);
      z-index: 2;
    }
    &:active {
      transform: scale(1);
      transition-duration: 0;
    }
  }
`

const StyledHomepage = styled.div`
  header,
  main {
    max-width: 1020px;
    margin: 0 auto;
  }
  header {
    margin: 2rem auto;
    .header-image {
      display: flex;
      justify-content: center;
    }
  }
  main {
    .vimeo-container {
      margin-bottom: 2rem;
      border: 1px solid orange;
      position: relative;
      .vimeo-loading {
        position: absolute;
        z-index: 2;
        background: black;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
      }
    }
    .video-gallery {
      margin-bottom: 4rem;
      &:hover {
        li {
          opacity: 0.5;
        }
      }
      ul {
        display: grid;
        grid-template-columns: 1fr 1fr 1fr 1fr;
        grid-template-rows: auto;
        grid-column-gap: 1rem;
        grid-row-gap: 1.5rem;
        flex-wrap: wrap;
      }
    }
  }
`;

export default Homepage;